# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

orbs:
  docker: circleci/docker@1.7.0
 
workflows:
  example-workflow:
    jobs:
      - docker/publish:
          dockerfile: dockerfile 
          image: nestdiscordbot 
          docker-username:  $DOCKER_LOGIN 
          docker-password:  $DOCKER_PASSWORD