version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: tomdatbenik/nestdiscordbot
    docker:
      - image: circleci/buildpack-deps:stretch
  node:
    docker:
      - image: cimg/node:16.13.1
jobs:
  test:
    executor: node
    steps:
      - checkout
      - run: npm i
      - run: npm run test
      - run: 
          name: check fail
          when: on_fail
          command: |
            echo "Canceling workflow as a step resulted in failure"
            curl -X POST --header "Content-Type: application/json" "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel?circle-token=$CIRCLE_TOKEN" 
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_LOGIN"
            echo "$DOCKER_LOGIN" | docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  tests:
   jobs:
      - test:
          name: tests
  build-main:
    jobs:
      - test:
          name: tests
      - build:
          filters:
            branches:
              only: main
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: main