# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
orbs:
  docker: circleci/docker@1.7.0

jobs:
  imajob:
    docker:
      - image: cimg/node:17.1.0  

workflows:
  version: 2
    docker-publish-workflow:
      jobs:
        - docker/publish:
            docker-username: $DOCKER_LOGIN  
            docker-password: $DOCKER_PASSWORD 
            dockerfile: dockerfile 
            image: nestdiscordbot 